spring:
  jpa:
    hibernate:
      ddl-auto: validate

jwt:
  expiration-minutes: 15

nginx:
  require-proxy: true

chirp-backend:
  rate-limit:
    ip:
      apply-limit: true
    email:
      apply-limit: true