spring:
  jpa:
    hibernate:
      ddl-auto: validate
  mail:
    host: smtp.mailgun.org
    username: chirptest@sandbox55cd8e9c7528461cab8dbbea33fb8c06.mailgun.org

jwt:
  expiration-minutes: 15

nginx:
  require-proxy: true

chirp-backend:
  email:
    url: "https://chirp-chat.com"
  rate-limit:
    ip:
      apply-limit: true
    email:
      apply-limit: true